[settings]
experimental = true

[tools]
go = "1.26.5"
node = "24.18.0"
"aqua:neovim/neovim" = "0.12.4"
"npm:@tailwindcss/language-server" = "0.16.0"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@doist/todoist-cli" = "3.0.2"
python = "3.14.6"
"npm:acpx" = "0.13.1"
"ubi:runkids/skillshare" = "0.20.22"
"aqua:openai/codex" = "latest"
worktrunk = "0.74.0"
"npm:@opencode/cli" = { version = "beta", npm_args = "--ignore-scripts=false" }
