[settings]
experimental = true

[tools]
go = "1.26.0"
node = "22.22.0"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:@openai/codex" = "0.114.0"
"npm:skills" = "1.3.9"
python = "3.14.3"
"ubi:runkids/skillshare" = "0.19.4"
