"$schema" = 'https://starship.rs/config-schema.json'

palette = "ayu_dark"

add_newline = false

[line_break]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[lua]
disabled = true

[dart]
disabled = true

[swift]
disabled = true

[kotlin]
disabled = true

[zig]
disabled = true

[docker_context]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[directory]
style = "bold teal"

[character]
success_symbol = "[\\$](overlay1)"
error_symbol = "[\\$](bold red)"

[git_branch]
symbol = "󰘬 "
style = "bold mauve"

[git_status]
style = "bold overlay2"
conflicted = "[✘](red)"
ahead = "[⇡](teal)"
behind = "[⇣](yellow)"
diverged = "[⇕](yellow)"
untracked = "[?](blue)"
stashed = "[\\$](teal)"
modified = "[!](peach)"
staged = "[+](green)"
deleted = "[✘](yellow)"
renamed = "[»](blue)"

[palettes.ayu_dark]
red = "#ea6c73"
maroon = "#f07178"
peach = "#ffb454"
yellow = "#e6b450"
green = "#aad94c"
teal = "#90e1c6"
sky = "#95e6cb"
blue = "#53bdfa"
sapphire = "#59c2ff"
mauve = "#cda1fa"
lavender = "#d2a6ff"
pink = "#cda1fa"
flamingo = "#f9af4f"
rosewater = "#e6b450"
text = "#bfbdb6"
subtext1 = "#bfbdb6"
subtext0 = "#9b9b9b"
overlay2 = "#686868"
overlay1 = "#686868"
overlay0 = "#4d5566"
surface2 = "#3d4455"
surface1 = "#1a1f29"
surface0 = "#11151c"
base = "#0b0e14"
mantle = "#0b0e14"
crust = "#0b0e14"
